# Generated by Django 6.0.8 on 2026-08-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_batch', models.CharField(db_index=True, max_length=100)),
                ('row_ref', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('raw_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['upload_batch', 'row_ref'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('clinic_id', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.CharField(db_index=True, max_length=100)),
                ('visit_id', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('doctor_id', models.CharField(db_index=True, max_length=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=10)),
                ('amount_paid_paise', models.IntegerField()),
                ('discount_paise', models.IntegerField(default=0)),
                ('is_refund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['clinic_id', 'timestamp'], name='core_billin_clinic__7f3c08_idx')],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_paise', models.IntegerField()),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.billingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('total_billed_paise', models.IntegerField()),
                ('total_collected_paise', models.IntegerField()),
                ('total_outstanding_paise', models.IntegerField()),
                ('total_refunds_paise', models.IntegerField()),
                ('visit_count', models.PositiveIntegerField()),
                ('refund_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('clinic_id', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='PaymentModeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=10)),
                ('billed_paise', models.IntegerField()),
                ('collected_paise', models.IntegerField()),
                ('outstanding_paise', models.IntegerField()),
                ('refunds_paise', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_payment_mode', to='core.reconciliationreport')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('REJECTED_RETRY', 'Rejected — retry'), ('FAILED_FALLBACK', 'Failed — fallback')], max_length=20)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recon_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_result', to='core.reconciliationreport')),
            ],
        ),
        migrations.CreateModel(
            name='TracedFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('display_value', models.CharField(max_length=200)),
                ('source_field', models.CharField(max_length=200)),
                ('narrative_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traced_figures', to='core.narrativeresult')),
            ],
            options={
                'ordering': ['placeholder'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('revenue_paise', models.IntegerField()),
                ('analytics_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_by_hour', to='core.analyticsreport')),
            ],
            options={
                'ordering': ['hour'],
                'unique_together': {('analytics_report', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='MedicineRankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('qty', 'By Quantity'), ('revenue', 'By Revenue')], max_length=10)),
                ('drug_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('analytics_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_ranks', to='core.analyticsreport')),
            ],
            options={
                'ordering': ['rank_type', 'rank'],
                'unique_together': {('analytics_report', 'rank_type', 'rank')},
            },
        ),
    ]
